Restaurant.create(name: 'Le Relais du gue de selle', address: 'Mezangers', category: 'french', phone_number: '06 52 94 44 84')
Restaurant.create(name: 'Aki', address: 'Paris', category: 'japanese', phone_number: '06 96 94 44 84')
Restaurant.create(name: 'Le Relais de la Malle', address: 'Laval', category: 'belgian', phone_number: '07 52 94 34 84')
Restaurant.create(name: 'Dazuma', address: 'Angers', category: 'chinese', phone_number: '06 52 94 38 64')
Restaurant.create(name: 'Les Petits Prés', address: 'Angers', category: 'french', phone_number: '06 10 14 44 84')
